<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>WinExe</OutputType>
    <RootNamespace>InputStitch</RootNamespace>
    <AssemblyName>InputStitch</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>InputStitch.ico</ApplicationIcon>
    <ApplicationVersion>1.0.0.0</ApplicationVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
    <Reference Include="netstandard" />
    <Reference Include="Nefarius.ViGEm.Client">
      <HintPath>third-party\Nefarius.ViGEm.Client\Nefarius.ViGEm.Client.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="InputStitch.cs" />
    <None Include="InputStitch.ico" />
    <None Include="app.manifest" />
    <EmbeddedResource Include="third-party\Nefarius.ViGEm.Client\Nefarius.ViGEm.Client.dll">
      <LogicalName>InputStitch.ThirdParty.Nefarius.ViGEm.Client.dll</LogicalName>
    </EmbeddedResource>
    <None Include="third-party\Nefarius.ViGEm.Client\LICENSE.txt" />
    <None Include="third-party\Nefarius.ViGEm.Client\ViGEmClient-LICENSE.txt" />
    <None Include="third-party\Nefarius.ViGEm.Client\Costura-LICENSE.txt" />
    <None Include="THIRD_PARTY_NOTICES.md" />
  </ItemGroup>
</Project>
